"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 07:28:58.402896
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code3', sa.String(length=3), nullable=True),
    sa.Column('name_de', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_norm', sa.String(length=100), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('aliases_norm', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('continent', sa.String(length=2), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('code', name=op.f('uq_countries_code'))
    )
    op.create_index(op.f('ix_countries_name_norm'), 'countries', ['name_norm'], unique=False)
    op.create_table('crawler_domains',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('crawl_delay_s', sa.Float(), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('robots_status', sa.Integer(), nullable=True),
    sa.Column('robots_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_count', sa.BigInteger(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_crawler_domains'))
    )
    op.create_table('geocode_cache',
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('query_hash', name=op.f('pk_geocode_cache'))
    )
    op.create_table('http_cache',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('body', sa.LargeBinary(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url_hash', name=op.f('pk_http_cache'))
    )
    op.create_index('ix_http_cache_fetched_at', 'http_cache', ['fetched_at'], unique=False)
    op.create_table('roles',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_roles'))
    )
    op.create_table('system_heartbeats',
    sa.Column('component', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('component', name=op.f('pk_system_heartbeats'))
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('geonames_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_de', sa.String(length=150), nullable=True),
    sa.Column('name_norm', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('aliases_norm', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_regions_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], name=op.f('fk_regions_parent_id_regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_regions_code')),
    sa.UniqueConstraint('country_id', 'name_norm', name=op.f('uq_regions_country_id_name_norm')),
    sa.UniqueConstraint('geonames_code', name=op.f('uq_regions_geonames_code'))
    )
    op.create_index('ix_regions_aliases_norm', 'regions', ['aliases_norm'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_regions_country_id'), 'regions', ['country_id'], unique=False)
    op.create_index(op.f('ix_regions_parent_id'), 'regions', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('username_norm', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_norm', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_key', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('avatar_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_users_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_key'], ['roles.key'], name=op.f('fk_users_role_key_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email_norm', name=op.f('uq_users_email_norm')),
    sa.UniqueConstraint('username_norm', name=op.f('uq_users_username_norm'))
    )
    op.create_index(op.f('ix_users_role_key'), 'users', ['role_key'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_website', sa.String(length=500), nullable=True),
    sa.Column('search_terms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('image_source', sa.String(length=32), nullable=True),
    sa.Column('image_source_url', sa.String(length=1000), nullable=True),
    sa.Column('image_version', sa.Integer(), nullable=False),
    sa.Column('image_locked', sa.Boolean(), nullable=False),
    sa.Column('image_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_status', sa.String(length=16), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_artists_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('slug', name=op.f('uq_artists_slug'))
    )
    op.create_index(op.f('ix_artists_name_norm'), 'artists', ['name_norm'], unique=False)
    op.create_index('ix_artists_name_norm_trgm', 'artists', ['name_norm'], unique=False, postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.create_index(op.f('ix_artists_next_crawl_at'), 'artists', ['next_crawl_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_de', sa.String(length=160), nullable=True),
    sa.Column('name_norm', sa.String(length=160), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('aliases_norm', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('geonames_id', sa.Integer(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_cities_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_cities_region_id_regions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('geonames_id', name=op.f('uq_cities_geonames_id'))
    )
    op.create_index('ix_cities_aliases_norm', 'cities', ['aliases_norm'], unique=False, postgresql_using='gin')
    op.create_index('ix_cities_country_name', 'cities', ['country_id', 'name_norm'], unique=False)
    op.create_index('ix_cities_name_norm_trgm', 'cities', ['name_norm'], unique=False, postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.create_index(op.f('ix_cities_region_id'), 'cities', ['region_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_channels_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('user_id', 'kind', 'name', name=op.f('uq_notification_channels_user_id_kind_name'))
    )
    op.create_index(op.f('ix_notification_channels_user_id'), 'notification_channels', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('remember', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('impersonated_user_id', sa.Integer(), nullable=True),
    sa.Column('impersonation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['impersonated_user_id'], ['users.id'], name=op.f('fk_sessions_impersonated_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('date_mode', sa.String(length=16), nullable=False),
    sa.Column('months_ahead', sa.SmallInteger(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('include_concerts', sa.Boolean(), nullable=False),
    sa.Column('include_support', sa.Boolean(), nullable=False),
    sa.Column('include_special', sa.Boolean(), nullable=False),
    sa.Column('festival_mode', sa.String(length=16), nullable=False),
    sa.Column('festival_scope', sa.String(length=16), nullable=False),
    sa.Column('show_cancelled', sa.Boolean(), nullable=False),
    sa.Column('show_unconfirmed', sa.Boolean(), nullable=False),
    sa.Column('default_show_festivals', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_filters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_filters')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq_user_filters_user_id_name'))
    )
    op.create_index(op.f('ix_user_filters_user_id'), 'user_filters', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('wallpaper', sa.String(length=64), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=True),
    sa.Column('animations', sa.Boolean(), nullable=False),
    sa.Column('transparency', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('view', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('artist_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('alias_norm', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_aliases_artist_id_artists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_aliases')),
    sa.UniqueConstraint('artist_id', 'alias_norm', name=op.f('uq_artist_aliases_artist_id_alias_norm'))
    )
    op.create_index(op.f('ix_artist_aliases_alias_norm'), 'artist_aliases', ['alias_norm'], unique=False)
    op.create_index(op.f('ix_artist_aliases_artist_id'), 'artist_aliases', ['artist_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_norm', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_tours_artist_id_artists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tours')),
    sa.UniqueConstraint('artist_id', 'name_norm', name=op.f('uq_tours_artist_id_name_norm'))
    )
    op.create_index(op.f('ix_tours_artist_id'), 'tours', ['artist_id'], unique=False)
    op.create_table('user_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('show_festivals', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('baseline_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_user_artists_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_artists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_artists')),
    sa.UniqueConstraint('user_id', 'artist_id', name=op.f('uq_user_artists_user_id_artist_id'))
    )
    op.create_index(op.f('ix_user_artists_artist_id'), 'user_artists', ['artist_id'], unique=False)
    op.create_index(op.f('ix_user_artists_user_id'), 'user_artists', ['user_id'], unique=False)
    op.create_table('user_cities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_user_cities_city_id_cities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['user_filters.id'], name=op.f('fk_user_cities_filter_id_user_filters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_cities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_cities')),
    sa.UniqueConstraint('filter_id', 'city_id', name=op.f('uq_user_cities_filter_id_city_id'))
    )
    op.create_index(op.f('ix_user_cities_city_id'), 'user_cities', ['city_id'], unique=False)
    op.create_index(op.f('ix_user_cities_user_id'), 'user_cities', ['user_id'], unique=False)
    op.create_table('user_countries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_user_countries_country_id_countries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['user_filters.id'], name=op.f('fk_user_countries_filter_id_user_filters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_countries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_countries')),
    sa.UniqueConstraint('filter_id', 'country_id', name=op.f('uq_user_countries_filter_id_country_id'))
    )
    op.create_index(op.f('ix_user_countries_country_id'), 'user_countries', ['country_id'], unique=False)
    op.create_index(op.f('ix_user_countries_user_id'), 'user_countries', ['user_id'], unique=False)
    op.create_table('user_regions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['user_filters.id'], name=op.f('fk_user_regions_filter_id_user_filters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_user_regions_region_id_regions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_regions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_regions')),
    sa.UniqueConstraint('filter_id', 'region_id', name=op.f('uq_user_regions_filter_id_region_id'))
    )
    op.create_index(op.f('ix_user_regions_region_id'), 'user_regions', ['region_id'], unique=False)
    op.create_index(op.f('ix_user_regions_user_id'), 'user_regions', ['user_id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('aliases_norm', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_venues_city_id_cities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_venues_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_index('ix_venues_aliases_norm', 'venues', ['aliases_norm'], unique=False, postgresql_using='gin')
    op.create_index('ix_venues_city_name', 'venues', ['city_id', 'name_norm'], unique=False)
    op.create_index('ix_venues_name_norm_trgm', 'venues', ['name_norm'], unique=False, postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_norm', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('aliases_norm', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('typical_month', sa.SmallInteger(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_festivals_city_id_cities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_festivals_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_festivals')),
    sa.UniqueConstraint('slug', name=op.f('uq_festivals_slug'))
    )
    op.create_index('ix_festivals_aliases_norm', 'festivals', ['aliases_norm'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_festivals_city_id'), 'festivals', ['city_id'], unique=False)
    op.create_index(op.f('ix_festivals_name_norm'), 'festivals', ['name_norm'], unique=False)
    op.create_index(op.f('ix_festivals_venue_id'), 'festivals', ['venue_id'], unique=False)
    op.create_table('user_venues',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['user_filters.id'], name=op.f('fk_user_venues_filter_id_user_filters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_venues_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_user_venues_venue_id_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_venues')),
    sa.UniqueConstraint('filter_id', 'venue_id', name=op.f('uq_user_venues_filter_id_venue_id'))
    )
    op.create_index(op.f('ix_user_venues_user_id'), 'user_venues', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_venues_venue_id'), 'user_venues', ['venue_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.SmallInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('doors_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ticket_status', sa.String(length=24), nullable=False),
    sa.Column('ticket_url', sa.String(length=1000), nullable=True),
    sa.Column('ticket_provider', sa.String(length=100), nullable=True),
    sa.Column('onsale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('city_name', sa.String(length=160), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_count', sa.SmallInteger(), nullable=False),
    sa.Column('best_trust', sa.SmallInteger(), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_source_url', sa.String(length=1000), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_events_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_events_city_id_cities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_events_country_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_events_festival_id_festivals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_events_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], name=op.f('fk_events_tour_id_tours'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_events_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_artist_date', 'events', ['artist_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_events_city_id'), 'events', ['city_id'], unique=False)
    op.create_index(op.f('ix_events_country_id'), 'events', ['country_id'], unique=False)
    op.create_index(op.f('ix_events_dedup_key'), 'events', ['dedup_key'], unique=False)
    op.create_index('ix_events_event_date', 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_festival_id'), 'events', ['festival_id'], unique=False)
    op.create_index('ix_events_listing', 'events', ['is_listed', 'is_confirmed', 'event_date'], unique=False)
    op.create_index(op.f('ix_events_region_id'), 'events', ['region_id'], unique=False)
    op.create_index(op.f('ix_events_tour_id'), 'events', ['tour_id'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('festival_id', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.SmallInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_type', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_event_count', sa.Integer(), nullable=True),
    sa.Column('last_method', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_sources_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_sources_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], name=op.f('fk_sources_festival_id_festivals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_sources_venue_id_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_artist_id'), 'sources', ['artist_id'], unique=False)
    op.create_index(op.f('ix_sources_festival_id'), 'sources', ['festival_id'], unique=False)
    op.create_index('ix_sources_next_attempt', 'sources', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_sources_provider'), 'sources', ['provider'], unique=False)
    op.create_index('ix_sources_scope_enabled', 'sources', ['scope', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_sources_venue_id'), 'sources', ['venue_id'], unique=False)
    op.create_table('crawler_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_crawler_jobs_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_crawler_jobs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_crawler_jobs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawler_jobs'))
    )
    op.create_index(op.f('ix_crawler_jobs_artist_id'), 'crawler_jobs', ['artist_id'], unique=False)
    op.create_index('ix_crawler_jobs_created_at', 'crawler_jobs', ['created_at'], unique=False)
    op.create_index('ix_crawler_jobs_queue', 'crawler_jobs', ['status', 'priority', 'run_after'], unique=False)
    op.create_index(op.f('ix_crawler_jobs_source_id'), 'crawler_jobs', ['source_id'], unique=False)
    op.create_index('uq_crawler_jobs_active_dedupe', 'crawler_jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('event_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('obs_key', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('trust_level', sa.SmallInteger(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('raw_title', sa.String(length=500), nullable=True),
    sa.Column('raw_venue', sa.String(length=300), nullable=True),
    sa.Column('raw_city', sa.String(length=200), nullable=True),
    sa.Column('raw_date', sa.String(length=100), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactive_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_sources_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_event_sources_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_sources')),
    sa.UniqueConstraint('source_id', 'obs_key', name=op.f('uq_event_sources_source_id_obs_key'))
    )
    op.create_index(op.f('ix_event_sources_event_id'), 'event_sources', ['event_id'], unique=False)
    op.create_index('ix_event_sources_source_active', 'event_sources', ['source_id', 'is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_notifications_artist_id_artists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name=op.f('uq_notifications_user_id_dedupe_key'))
    )
    op.create_index(op.f('ix_notifications_artist_id'), 'notifications', ['artist_id'], unique=False)
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('ticket_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trust_level', sa.SmallInteger(), nullable=False),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_sources_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_sources')),
    sa.UniqueConstraint('event_id', 'url', name=op.f('uq_ticket_sources_event_id_url'))
    )
    op.create_index(op.f('ix_ticket_sources_event_id'), 'ticket_sources', ['event_id'], unique=False)
    op.create_table('crawler_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sources_total', sa.Integer(), nullable=False),
    sa.Column('sources_ok', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('events_found', sa.Integer(), nullable=False),
    sa.Column('events_new', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('events_removed', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_crawler_runs_artist_id_artists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['crawler_jobs.id'], name=op.f('fk_crawler_runs_job_id_crawler_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_crawler_runs_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawler_runs'))
    )
    op.create_index(op.f('ix_crawler_runs_artist_id'), 'crawler_runs', ['artist_id'], unique=False)
    op.create_index(op.f('ix_crawler_runs_job_id'), 'crawler_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawler_runs_source_id'), 'crawler_runs', ['source_id'], unique=False)
    op.create_index('ix_crawler_runs_started_at', 'crawler_runs', ['started_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_notification_deliveries_channel_id_notification_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('notification_id', 'channel_id', name=op.f('uq_notification_deliveries_notification_id_channel_id'))
    )
    op.create_index(op.f('ix_notification_deliveries_channel_id'), 'notification_deliveries', ['channel_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_notification_id'), 'notification_deliveries', ['notification_id'], unique=False)
    op.create_table('crawler_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_crawler_errors_artist_id_artists'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['crawler_jobs.id'], name=op.f('fk_crawler_errors_job_id_crawler_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['crawler_runs.id'], name=op.f('fk_crawler_errors_run_id_crawler_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_crawler_errors_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawler_errors'))
    )
    op.create_index(op.f('ix_crawler_errors_artist_id'), 'crawler_errors', ['artist_id'], unique=False)
    op.create_index('ix_crawler_errors_occurred_at', 'crawler_errors', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_crawler_errors_run_id'), 'crawler_errors', ['run_id'], unique=False)
    op.create_index(op.f('ix_crawler_errors_source_id'), 'crawler_errors', ['source_id'], unique=False)
    # ### end Alembic commands ###
    roles = sa.table(
        "roles",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("permissions", postgresql.JSONB),
    )
    op.bulk_insert(
        roles,
        [
            {"key": "user", "name": "Benutzer", "description": "Verwaltet eigene Künstler, Filter und Einstellungen", "permissions": []},
            {"key": "admin", "name": "Administrator", "description": "Vollzugriff auf Benutzer, Crawler und System", "permissions": ["*"]},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawler_errors_source_id'), table_name='crawler_errors')
    op.drop_index(op.f('ix_crawler_errors_run_id'), table_name='crawler_errors')
    op.drop_index('ix_crawler_errors_occurred_at', table_name='crawler_errors')
    op.drop_index(op.f('ix_crawler_errors_artist_id'), table_name='crawler_errors')
    op.drop_table('crawler_errors')
    op.drop_index(op.f('ix_notification_deliveries_notification_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_channel_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_crawler_runs_started_at', table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_source_id'), table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_job_id'), table_name='crawler_runs')
    op.drop_index(op.f('ix_crawler_runs_artist_id'), table_name='crawler_runs')
    op.drop_table('crawler_runs')
    op.drop_index(op.f('ix_ticket_sources_event_id'), table_name='ticket_sources')
    op.drop_table('ticket_sources')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_artist_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_event_sources_source_active', table_name='event_sources')
    op.drop_index(op.f('ix_event_sources_event_id'), table_name='event_sources')
    op.drop_table('event_sources')
    op.drop_index('uq_crawler_jobs_active_dedupe', table_name='crawler_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_crawler_jobs_source_id'), table_name='crawler_jobs')
    op.drop_index('ix_crawler_jobs_queue', table_name='crawler_jobs')
    op.drop_index('ix_crawler_jobs_created_at', table_name='crawler_jobs')
    op.drop_index(op.f('ix_crawler_jobs_artist_id'), table_name='crawler_jobs')
    op.drop_table('crawler_jobs')
    op.drop_index(op.f('ix_sources_venue_id'), table_name='sources')
    op.drop_index('ix_sources_scope_enabled', table_name='sources')
    op.drop_index(op.f('ix_sources_provider'), table_name='sources')
    op.drop_index('ix_sources_next_attempt', table_name='sources')
    op.drop_index(op.f('ix_sources_festival_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_artist_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_tour_id'), table_name='events')
    op.drop_index(op.f('ix_events_region_id'), table_name='events')
    op.drop_index('ix_events_listing', table_name='events')
    op.drop_index(op.f('ix_events_festival_id'), table_name='events')
    op.drop_index('ix_events_event_date', table_name='events')
    op.drop_index(op.f('ix_events_dedup_key'), table_name='events')
    op.drop_index(op.f('ix_events_country_id'), table_name='events')
    op.drop_index(op.f('ix_events_city_id'), table_name='events')
    op.drop_index('ix_events_artist_date', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_user_venues_venue_id'), table_name='user_venues')
    op.drop_index(op.f('ix_user_venues_user_id'), table_name='user_venues')
    op.drop_table('user_venues')
    op.drop_index(op.f('ix_festivals_venue_id'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_name_norm'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_city_id'), table_name='festivals')
    op.drop_index('ix_festivals_aliases_norm', table_name='festivals', postgresql_using='gin')
    op.drop_table('festivals')
    op.drop_index('ix_venues_name_norm_trgm', table_name='venues', postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.drop_index('ix_venues_city_name', table_name='venues')
    op.drop_index('ix_venues_aliases_norm', table_name='venues', postgresql_using='gin')
    op.drop_table('venues')
    op.drop_index(op.f('ix_user_regions_user_id'), table_name='user_regions')
    op.drop_index(op.f('ix_user_regions_region_id'), table_name='user_regions')
    op.drop_table('user_regions')
    op.drop_index(op.f('ix_user_countries_user_id'), table_name='user_countries')
    op.drop_index(op.f('ix_user_countries_country_id'), table_name='user_countries')
    op.drop_table('user_countries')
    op.drop_index(op.f('ix_user_cities_user_id'), table_name='user_cities')
    op.drop_index(op.f('ix_user_cities_city_id'), table_name='user_cities')
    op.drop_table('user_cities')
    op.drop_index(op.f('ix_user_artists_user_id'), table_name='user_artists')
    op.drop_index(op.f('ix_user_artists_artist_id'), table_name='user_artists')
    op.drop_table('user_artists')
    op.drop_index(op.f('ix_tours_artist_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_artist_aliases_artist_id'), table_name='artist_aliases')
    op.drop_index(op.f('ix_artist_aliases_alias_norm'), table_name='artist_aliases')
    op.drop_table('artist_aliases')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_filters_user_id'), table_name='user_filters')
    op.drop_table('user_filters')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notification_channels_user_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_cities_region_id'), table_name='cities')
    op.drop_index('ix_cities_name_norm_trgm', table_name='cities', postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.drop_index('ix_cities_country_name', table_name='cities')
    op.drop_index('ix_cities_aliases_norm', table_name='cities', postgresql_using='gin')
    op.drop_table('cities')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_artists_next_crawl_at'), table_name='artists')
    op.drop_index('ix_artists_name_norm_trgm', table_name='artists', postgresql_using='gin', postgresql_ops={'name_norm': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_artists_name_norm'), table_name='artists')
    op.drop_table('artists')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_users_role_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_parent_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_country_id'), table_name='regions')
    op.drop_index('ix_regions_aliases_norm', table_name='regions', postgresql_using='gin')
    op.drop_table('regions')
    op.drop_table('system_heartbeats')
    op.drop_table('roles')
    op.drop_index('ix_http_cache_fetched_at', table_name='http_cache')
    op.drop_table('http_cache')
    op.drop_table('geocode_cache')
    op.drop_table('crawler_domains')
    op.drop_index(op.f('ix_countries_name_norm'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
