"""Post-process the autogenerated initial migration (extensions + base data)."""
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
src = path.read_text()
if "CREATE EXTENSION" not in src:
    src = src.replace(
        "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n",
        "def upgrade() -> None:\n"
        "    op.execute(\"CREATE EXTENSION IF NOT EXISTS pg_trgm\")\n"
        "    # ### commands auto generated by Alembic - please adjust! ###\n",
        1,
    )
    src = re.sub(
        r"(\n    # ### end Alembic commands ###\n)(\n\ndef downgrade)",
        "\\1"
        "    roles = sa.table(\n"
        "        \"roles\",\n"
        "        sa.column(\"key\", sa.String),\n"
        "        sa.column(\"name\", sa.String),\n"
        "        sa.column(\"description\", sa.String),\n"
        "        sa.column(\"permissions\", postgresql.JSONB),\n"
        "    )\n"
        "    op.bulk_insert(\n"
        "        roles,\n"
        "        [\n"
        "            {\"key\": \"user\", \"name\": \"Benutzer\", \"description\": \"Verwaltet eigene Künstler, Filter und Einstellungen\", \"permissions\": []},\n"
        "            {\"key\": \"admin\", \"name\": \"Administrator\", \"description\": \"Vollzugriff auf Benutzer, Crawler und System\", \"permissions\": [\"*\"]},\n"
        "        ],\n"
        "    )\n"
        "\\2",
        src,
        count=1,
    )
path.write_text(src)
print("patched", path)
